#!/bin/bash
#
# Firewall using iptables
#
# Copyright (c) T. Zengerink
# Lisenced under MIT Lisence
# Visit: https://raw.github.com/Mytho/iptables-firewall/master/license.txt

set -e
DIR="$(cd "$(dirname $0)" && pwd)"
IPT="$(which iptables)"
CNF="$DIR/firewall.conf"
WL="$DIR/firewall.whitelist"
BL="$DIR/firewall.blacklist"

## -- FLUSH --------------------------------------------------------------------

flush_firewall(){
	$IPT -F
	$IPT -X
}

## -- START --------------------------------------------------------------------

start_firewall(){
	echo -e "Starting firewall..."

	# Creating neccesary chains
	$IPT -N TCP
	$IPT -N UDP
	$IPT -P FORWARD DROP
	$IPT -P OUTPUT ACCEPT
	#$IPT -P INTPUT DROP
}

## -- STATUS -------------------------------------------------------------------

status_firewall(){
	echo -e "Firewall Status:"
}

## -- STOP ---------------------------------------------------------------------

stop_firewall(){
	$IPT -P INPUT ACCEPT
	$IPT -P FORWARD ACCEPT
	$IPT -P OUTPUT ACCEPT
}

## -- EXECUTE ------------------------------------------------------------------

if [ ! -f $CNF ]; then
	echo "Unable to load configuration file ($CNF)... Exiting"
	exit 0
fi
source $CNF

case "$1" in
	flush)
		flush_firewall
		;;
	start|restart)
		flush_firewall
		start_firewall
		;;
	status)
		status_firewall
		;;
	stop)
		flush_firewall
		stop_firewall
		;;
	*)
		echo -e "Usage: $0 [flush|restart|start|status|stop]"
		exit 1
esac

exit 0
