#!/bin/bash
#
# Firewall using iptables
#
# Copyright (c) T. Zengerink
# Lisenced under MIT Lisence
# Visit: https://raw.github.com/Mytho/iptables-firewall/master/license.txt

set -e
DIR="$(cd "$(dirname $0)" && pwd)"
IPT="$(which iptables)"
CNF="$DIR/firewall.conf"

## -- START --------------------------------------------------------------------

start_firewall(){
	echo -e "Starting firewall..."
}

## -- STOP ---------------------------------------------------------------------

stop_firewall(){
	echo -e "Stopping firewall..."
}

## -- STATUS -------------------------------------------------------------------

status_firewall(){
	echo -e "Firewall Status"
}

## -- EXECUTE ------------------------------------------------------------------

if [ ! -f $CNF ]; then
	echo "Unable to load configuration file ($CNF)... Exiting"
	exit 0
fi
source $CNF

case "$1" in
	start)
		start_firewall
		;;
	stop)
		stop_firewall
		;;
	status)
		status_firewall
		;;
	restart)
		stop_firewall
		start_firewall
		;;
	*)
		echo -e "Usage: $0 [start|stop|status|restart]"
		exit 1
esac

exit 0
